@BASE=http://127.0.0.1:81

### 
GET {{BASE}}/healthz
Content-Type: application/json

### 
GET {{BASE}}/healthz
Content-Type: application/json
X-Request-Rt: 2

### 
GET {{BASE}}/healthz
Content-Type: application/json
X-Request-Rt: 3

### 
GET {{BASE}}/?action=healthz
Content-Type: application/json

// -----------------------------------------------
// hello

### 
GET {{BASE}}/?action=hello
Content-Type: application/json

### 
GET {{BASE}}/world
Content-Type: application/json

### 
POST {{BASE}}/world
Content-Type: application/json

### 
GET {{BASE}}/token
Content-Type: application/json
Authorization: Token 123

### 
GET {{BASE}}/token
Content-Type: application/json
Authorization: Token 1234

// -----------------------------------------------
// front2

### 
GET {{BASE}}/1/2/3

### 
GET {{BASE}}/zgg/1/2/3

### 
GET {{BASE}}/demo/1/2/3

### 
GET {{BASE}}/demo/1/2/3.txt

### 
GET {{BASE}}/site/list123456

### 
GET {{BASE}}/api1/test


// -----------------------------------------------
// kwdog2

