@BASE=http://127.0.0.1:81

### 
GET {{BASE}}/healthz
Content-Type: application/json

### 
GET {{BASE}}/healthz
Content-Type: application/json
X-Request-Rt: 2

### 
GET {{BASE}}/healthz
Content-Type: application/json
X-Request-Rt: 3

### 
GET {{BASE}}/?action=healthz
Content-Type: application/json

// -----------------------------------------------
// hello

### 
GET {{BASE}}/?action=hello
Content-Type: application/json

### 
GET {{BASE}}/world
Content-Type: application/json

### 
POST {{BASE}}/world
Content-Type: application/json

### 
GET {{BASE}}/token
Content-Type: application/json
Authorization: Token 123

### 
GET {{BASE}}/token
Content-Type: application/json
Authorization: Token 1234

// -----------------------------------------------
// front2

### 
GET {{BASE}}/1/2/3

### 
GET {{BASE}}/zgg/1/2/3

### 
GET {{BASE}}/demo/1/2/3

### 
GET {{BASE}}/demo/1/2/3.txt

### 
GET {{BASE}}/site/list123456

### 
GET {{BASE}}/api1/test


// -----------------------------------------------
// kwdog2

### 其他服务
GET {{BASE}}/api/iam/v1/a/odic/user_info
Cookie: _xc=XC.1.00.1766767400.f1kin.9fyokoanxvi2
Referer: https://xxx.xxx.com/
Content-Type: application/json
Authorization: Bearer kst.9B8A147880FE5434E281C58CDF2EC43E00000002WL90PxBIoL0y2iJ7OkFmbBxBT_xufjshdyz1l4.1000001.p6m.t5_f54b93064451


### 后端服务
GET {{BASE}}/api/pas/v1/enums/app/status
Cookie: _xc=XC.1.00.1766767400.f1kin.9fyokoanxvi2
Referer: https://xxx.xxx.com/
Content-Type: application/json
Authorization: Bearer kst.9B8A147880FE5434E281C58CDF2EC43E00000002WL90PxBIoL0y2iJ7OkFmbBxBT_xufjshdyz1l4.1000001.p6m.t5_f54b93064451



### 
POST {{BASE}}/api/test?flow=abc
Host: kwdog.com
Cookie: _xc=XC.1.00.1766767400.f1kin.9fyokoanxvi2
Referer: https://xxx.xxx.com/
Content-Type: application/json
Authorization: Bearer kst.9B8A147880FE5434E281C58CDF2EC43E00000002WL90PxBIoL0y2iJ7OkFmbBxBT_xufjshdyz1l4.1000001.p6m.t5_f54b93064451

{
    "name": "kwdog"
}

// -----------------------------------------------
// kwlog2
### 
POST {{BASE}}/api/logs
Content-Type: application/json
Authorization: Token xxx123456789
X-Request-Tag: test.dev

[{
    "__time": 1625.425043,
    "_time": "2025-12-28T10:06:39.425043028Z",
    "_ktag": "stderr",
    "message": "[2025-12-28 10:06:39 +0000] [8] [INFO] Booting worker with pid: 8\u1234",
    "__pod_name": "httpbin-69bf8fdb78-rcs4h",
    "__namespace_name": "default",
    "__node_name": "dev-master",
    "__pod_ip": "10.42.0.122",
    "__container_name": "httpbin-logtty",
    "__container_image": "docker.io/kong/httpbin:0.2.3",
    "__app_name": "httpbin"
}]