name: 'Build Image Logic'
description: 'Build image steps for jobs'

inputs:
  docker_user:
    description: 'docker.io user name'
    required: true
  docker_token:
    description: 'docker.io user token'
    required: true
    secret: true

# env:
#   IMAGE_NAME: suisrc/k8skit
#   GITHUB_REGISTRY: ghcr.io
#   DOCKER_REGISTRY: docker.io
#   IMAGE_VERSION: "`cat app/version`-`cat app/vname`"

runs:
  using: 'composite'
  steps:
    - name: Build app.version
      shell: bash
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo ${TAG_NAME#v} > app/version
        echo $GITHUB_JOB > app/vname
        echo "IMAGE_VERSION=${TAG_NAME#v}-$GITHUB_JOB" >> $GITHUB_ENV
    - name: Build image
      shell: bash
      run: |
        echo "appname: `cat app/vname`, version: `cat app/version`"
        sed -i "s|zgg|`cat app/vname`|g" Dockerfile
        make `cat app/vname` && docker build -t image --no-cache .
    - name: Push github image
      shell: bash
      run: |
        REGISTRY_URL=$GITHUB_REGISTRY
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin
        IMAGE_ID=$REGISTRY_URL/$GITHUB_REPOSITORY
        echo IMAGE_ID=$IMAGE_ID
        VERSION=$IMAGE_VERSION
        echo VERSION=$VERSION
        docker tag image $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
    - name: Push docker image
      shell: bash
      run: |
        REGISTRY_URL=$DOCKER_REGISTRY
        echo "${{ inputs.docker_token }}" | docker login $REGISTRY_URL -u ${{ inputs.docker_user }} --password-stdin
        IMAGE_ID=$REGISTRY_URL/$IMAGE_NAME
        echo IMAGE_ID=$IMAGE_ID
        VERSION=$IMAGE_VERSION
        echo VERSION=$VERSION
        docker tag image $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
